### ISSUE TITLE
Document how to publish to a topic

### ISSUE THREAD

**Issue by rstento** [lightbend/akkaserverless-java-sdk#122]
From @patriknw: Can't see that we describe how to publish to a topic in topic-eventing.adoc?

From @ennru: Correct, that is pending. My idea would be to add an external publish on cart checkout.
That's a good place to show entity id access in a listener.

From @viktorklang: @rstento I want to raise this as a very high priority for Open Beta. Not being able to publish messages makes the Eventing functionality very, very, limited.

**Comment by octonato** [comment]
done in #373
