### ISSUE TITLE
Java: Explain what the context means and what it contains

### ISSUE THREAD

**Issue by rstento** [lightbend/akkaserverless-java-sdk#126]
@retgits commented on [Thu May 27 2021](https://github.com/lightbend/akkaserverless-docs/issues/581)

> Many of the developers would come from a CRUD approach and it would be hard for them to get a grasp on Event Sourcing and the Java Classes related to it. Maybe we could do something to help them out? They could have questions like, why am I using akkaserverless.field? We have context like EntityContext, CommandContext, EffectContext etc but what exactly is this context?

**Comment by patriknw** [comment]
Contex is becoming less relevant with the new API. We should wait with this until after the SDK changes have been completed.
