### ISSUE TITLE
Ambiguous definition of proto namespace

### ISSUE THREAD

**Issue by rstento** [lightbend/akkaserverless-java-sdk#128]
@rstento commented on [Thu Jul 08 2021](https://github.com/lightbend/akkaserverless-javascript-sdk/issues/111)

@mckeeh3 commented on [Mon Jun 07 2021](https://github.com/lightbend/akkaserverless-docs/issues/636)

In [The service proto file](https://docs.akkaserverless.dev/java-services/proto.html#_the_service_proto_file) section of the docs.

This sentence:

The package specifies a namespace for this proto file and its imports—names must be unique within each namespace:

What is this namespace used for? This is confusing. How is this namespace used? Does it only apply to the proto files? Or is the namespace used in code as well?

**Comment by rstento** [comment]
@pvlugter, can you answer @mckeeh3's question by commenting here?

**Comment by retgits** [comment]
The package name for .proto file, quite similar to the package name in Java, groups elements of a .proto file together. It's the unique classifier that helps to prevent name clashes between protocol message types. As an example, if I have `message1` in both `api.proto` and `domain.proto` the protobuf compiler wouldn't know which of the two you want to use when you specify `message1`. Adding a package name helps prevent that conflict.

For Java, the protobuf compiler uses the package name (unless you specify `option java_package`) as the package name for your generated code too. There are languages where the package name doesn't directly affect the generated code but it is still a good practice to specify the package name to avoid conflicts when your proto files are used to generate client code for languages that do rely on it.

**Comment by rstento** [comment]
Thanks @retgits!

**Comment by ennru** [comment]
Outdated.
