### ISSUE TITLE
Use consistent proto file naming convention

### ISSUE THREAD

**Issue by rstento** [lightbend/akkaserverless-java-sdk#129]
@mckeeh3 commented on [Mon Jun 07 2021](https://github.com/lightbend/akkaserverless-docs/issues/639)

In the [Writing gRPC descriptors](https://docs.akkaserverless.dev/java-services/proto.html) section of the docs, the proto file naming convention is inconsistent with other parts of the documentation. 

Use "API" and "domain" suffixes for proto file names. Also, use dash versus underscore in file names. 

Examples
* shopping-cart-api.proto
* shopping-cart-domain.proto

**Comment by patriknw** [comment]
According to the style guide https://developers.google.com/protocol-buffers/docs/style:

> Files should be named lower_snake_case.proto

**Comment by rstento** [comment]
In the samples directory, it looks like all examples are using the style referenced by @patriknw in the previous comment. However, we don't have a plain shopping cart proto example, we have a value entity and an event sourced entity cart example. The proto overview page could be updated with both, using tabs or we could pick one.
