### ISSUE TITLE
Add gRPC API example to Implementing Event Sourced Entities in Java

### ISSUE THREAD

**Issue by rstento** [lightbend/akkaserverless-java-sdk#133]
@mckeeh3 commented on [Wed Jun 09 2021](https://github.com/lightbend/akkaserverless-docs/issues/668)

Need a gRPC API example in [Implementing Event Sourced Entities in Java](https://docs.akkaserverless.dev/java-services/eventsourced.html). 

This is needed to help to relate the API definition to the event source entity implementation code examples.

**Comment by patriknw** [comment]
I think this is covered in the updated docs.
