### ISSUE TITLE
Support one API with two implementations in the same project

### ISSUE THREAD

**Issue by raboof** [lightbend/akkaserverless-java-sdk#169]
Previously, before going all-in on codegen, it was possible to have two implementations of the same API, for example a value-entity based one and an event-sourced-entity based one like in the java-customer-registry sample.

This currently doesn't work with codegen, and it's debatable whether that is something we'd like to bring back.

**Comment by johanandren** [comment]
It's very unclear to me in what situation that would be valuable (even the sample was just us being lazy AFAICS).

**Comment by octonato** [comment]
I agree we that we should not support this because of it's low (probably zero) value. And it will add complexity to the codegen since we rely on a protobuf annotation decide which kind of entity to generate.

**Comment by patriknw** [comment]
I have already split up  java-customer-registry into two samples when enabling codegen for all of it.

I agree that this feature is not needed, (until asked for). Let's close.
