### ISSUE TITLE
archetype does not work

### ISSUE THREAD

**Issue by raboof** [lightbend/akkaserverless-java-sdk#173]
On a clean system, the command documented at https://developer.lightbend.com/docs/akka-serverless/java/kickstart.html :

```
mvn archetype:generate -DarchetypeGroupId=com.akkaserverless -DarchetypeArtifactId=akkaserverless-maven-archetype -DarchetypeVersion=LATEST
```

... does not work. The symptoms can be confusing: the logging sometimes looks as if it can't find the LATEST version or it can't find the archetype jar. Looking closer the LATEST version is actually correctly resolved and the archetype found, but the archetype's parent pom was not correctly published.

**Comment by pvlugter** [comment]
Works with the latest (beta.18) release now.
