### ISSUE TITLE
Don't generate the domain and api twice when testing

### ISSUE THREAD

**Issue by raboof** [lightbend/akkaserverless-java-sdk#182]
The `valueentity-counter` sample uses a second execution of the `protobuf-maven-plugin` plugin on the test-compile goal to generate the Akka gRPC service client used for testing. However, it also generates the API and Domain classes again.

That is unnecessary, we should see if it is somehow possible to disable the generation of the plain Java classes in this execution, and only generate the akka-grpc code.

**Comment by johanandren** [comment]
Should not happen anymore since we moved gRPC client generation to the default phase? (in #389 )

**Comment by raboof** [comment]
I think this is a Maven ticket, so it wouldn't be solved by #389. However, I *think* we moved generating the Akka gRPC client from 'test' to 'main' on Maven, too, so it's very possible this issue has been fixed then. Perhaps double-check then close?

**Comment by johanandren** [comment]
In that PR (which maybe looks a bit much like only about docs) I changed all the samples and the maven archetype to not hook gRPC client generation into the `it` phase but to do that by default, so that gRPC clients are always generated, so that's why I think it should fix this issue.

**Comment by raboof** [comment]
Huh I'm not sure what I was thinking. Sounds good!
