### ISSUE TITLE
Add Replicated Entity page back to Java SDK doc pages

### ISSUE THREAD

**Issue by rstento** [lightbend/akkaserverless-java-sdk#187]
@rstento commented on [Mon Aug 02 2021](https://github.com/lightbend/akkaserverless-docs/issues/818)

**Comment by rstento** [comment]
This task brings back the old documentation on replicated entities, but it still needs to be updated to reflect the new implementation.

**Comment by pvlugter** [comment]
And waiting for some more changes to be merged for the updated implementation (#161, which depends on a proxy release with https://github.com/lightbend/akkaserverless-framework/pull/803).

**Comment by rstento** [comment]
Closing this because the implemention is not complete yet. And, it has changed so much, it makes more sense for the developers to create the first draft instead of reusing the old one.
