### ISSUE TITLE
View codegen must add `UpdateHandler` to method signatures

### ISSUE THREAD

**Issue by ennru** [lightbend/akkaserverless-java-sdk#199]
The current codegen for Views creates message signatures for update handlers with the incoming event and the state as `Optional` in the abstract base class. 

Logic that requires access to the `UpdateHandlerContext` can't use codegen.

**Comment by raboof** [comment]
I think the context will move to the abstract superclass as part of #52 anyway. Do we want to fix this on `main` before we finish and merge #52?

**Comment by patriknw** [comment]
This is fixed by new codegen.
