### ISSUE TITLE
Various kickstart instructions incorrect

### ISSUE THREAD

**Issue by rstento** [lightbend/akkaserverless-java-sdk#205]
The doc says:
Open the IDE, select File > New > Project, and click to activate Create from archetype. Use the UI to locate the archetype and fill in the blanks.

After selecting File > New > Project, you need to select Maven, then you can see the checkbox for Create from archetype. And, you can't locate the archetype if it is not already in your list, instead you need to add it, using the groupID, artifactID, and version.  All of this page should be checked. If you use IntelliJ, the generated source files are not in the location documented. It might be that this is incorrect if you use the command line to run Maven as well. And the readme generated in the Kickstart project contains broken links and could be more useful.

**Comment by rstento** [comment]
In addition, the ^ characters in the command to run maven makes the command fail when copied from the doc. We need to test whether the command works OK without the ^ characters on separate lines, or whether it should just all be put on one line.

In addition, we do not tell the user what they should use when maven prompts them for projectId etc. We should make a "for example," suggestion.

**Comment by johanandren** [comment]
I think this is no longer relevant with the new quickstarts (checked at least one without finding these issues)
