### ISSUE TITLE
View class name clashes between Akka gRPC and Akka Serverless

### ISSUE THREAD

**Issue by raboof** [lightbend/akkaserverless-java-sdk#207]
Both Akka Serverless and Akka gRPC generate a class that matches the package and service names of the view from the `.proto` (i.e. `view.CustomerByName`): Akka Serverless for the implementation, and Akka gRPC for the public API.

Akka Serverless does not allow choosing a different class name, because it is referenced from the generated 'registrations'.

You would expect to have the same problem with entities. However, in that case the Akka Serverless implementation name is not derived from the `service` (i.e. `api.CustomerService`) but from the component implementing the service (i.e. `domain.Customer`). Unfortunately, views don't have an equivalent in the `proto`: just the `service` is sufficient in that case.

**Comment by raboof** [comment]
it's tempting to add some kind of suffix, like `Impl` (but we just recently removed that in #111) or `View`. Appending `View` would be awkward when the proto service already has `View` in the name (causing `CustomerByNameViewView`), but for our examples we're recommending putting the views in their own package, which perhaps makes this problem less likely to occur? Making it customizable feels a bit like overkill but could be an 'escape hatch' in the future.

**Comment by patriknw** [comment]
The best I can think of right now is to add the `View` suffix. We could have a fallback for the ViewView case and then use ViewImpl instead.
