### ISSUE TITLE
JavadocGenerationFailed

### ISSUE THREAD

**Issue by patriknw** [lightbend/akkaserverless-java-sdk#212]
I tried `publishLocal` with jdk 11:

```
[error] (sdk / Compile / doc) sbt.inc.Doc$JavadocGenerationFailed

[error] compiler message file broken: key=javadoc.err.msg arguments=javadoc, invalid flag: --no-module-directories, {2}, {3}, {4}, {5}, {6}, {7}
```

Also tried with jdk 8:
```
IllegalArgumentException: invalid flag: --release
```

**Comment by raboof** [comment]
> invalid flag: --no-module-directories

That's weird, that flag should definitely be there on jdk11 (we use it on akka as well AFAICS, https://github.com/akka/akka/blob/master/project/Doc.scala#L138-L139

**Comment by raboof** [comment]
`sbt publishLocal` works for me with jdk11 - are you sure you're not on a later jvm? on jdk16 I can reproduce that problem, https://github.com/akka/akka/pull/30368 .

**Comment by patriknw** [comment]
ah, `welcome to sbt 1.4.9 (Homebrew Java 16.0.2)`

That's weird because from terminal:
```
javac -version
javac 11.0.11
```

**Comment by patriknw** [comment]
Fixed, thanks.
