### ISSUE TITLE
Update documentation to use the new codgen

### ISSUE THREAD

**Issue by patriknw** [lightbend/akkaserverless-java-sdk#222]
- [x] actions.adoc (@octonato)
- [x] api.adoc (@patriknw) 
- [x] entity-eventing.adoc (@octonato) - replaced by "Publishing and Subscribing with Actions"
- [x] eventsourced.adoc (@patriknw)
- [x] forwarding.adoc (@octonato) - replaced by "Actions as Controllers" and "Running Side Effects"
- [x] kickstart.adoc (@patriknw)
- [x] proto.adoc (@patriknw)
- [x] serialization.adoc (@patriknw)
- [x] topic-eventing.adoc (@octonato) - replaced by "Publishing and Subscribing with Actions"
- [x] value-entity.adoc (@patriknw)
- [x] views.adoc (@patriknw)
- [x] development-process-java.adoc (@patriknw)
- [x] archetype / first-service (@patriknw)
- [x] Quickstart https://github.com/lightbend/akkaserverless-docs/tree/master/docs/modules/quickstart/pages (@patriknw)

See https://github.com/lightbend/akkaserverless-java-sdk/issues/52

**Comment by octonato** [comment]
All subtasks are completed, closing this.
