### ISSUE TITLE
forwarding note confusing

### ISSUE THREAD

**Issue by rstento** [lightbend/akkaserverless-java-sdk#226]
@marcoderama commented on [Thu Aug 19 2021](https://github.com/lightbend/akkaserverless-docs/issues/856)

The "Important" note near the top of https://developer.lightbend.com/docs/akka-serverless/java/forwarding.html is confused.  (Source in https://github.com/lightbend/akkaserverless-docs/blob/master/docs/modules/developing/partials/forwarding.adoc I believe.)  It contains...

> [...] ​there is no guarantee that any one sent transactions will succeeded.

I'm not exactly sure how to fix that but it's clearly unclear.

**Comment by johanandren** [comment]
Hopefully improved with the new forwarding doc page.
