### ISSUE TITLE
Typo in Java example for emitting events

### ISSUE THREAD

**Issue by rstento** [lightbend/akkaserverless-java-sdk#227]
@marcoderama commented on [Thu Aug 19 2021](https://github.com/lightbend/akkaserverless-docs/issues/855)

The sample code at https://developer.lightbend.com/docs/akka-serverless/java/eventsourced.html#_emitting_events contains the line:
`throw context.fail("Cannot add negative quantity of to item" + item.getProductId());`

That should be something like:
`throw context.fail("Quantity for item " + item.getProductId() + " must be greater than zero.");`

cf. PR https://github.com/lightbend/akkaserverless-java-sdk/pull/220

**Comment by johanandren** [comment]
No longer in that sample as far as I can see.

**Comment by marcoderama** [comment]
Yeah.  I think this PR https://github.com/lightbend/akkaserverless-java-sdk/pull/220 fixed it.  Forgot to close the issue.
