### ISSUE TITLE
Find better solution for Views and Actions name clashes

### ISSUE THREAD

**Issue by octonato** [lightbend/akkaserverless-java-sdk#238]
_Triggered by https://github.com/lightbend/akkaserverless-java-sdk/pull/237#r695602525_

Views and Actions are generated from the gRPC service define in the proto file and that clashes with the service generated by akka-grpc. 

That can be surprising for users. They define a service like HelloService, but get a HelloServiceAction instead. Or they call it HelloAction, but get a HelloActionImpl. 

And they end up with HelloAction.java (generated by akka-grpc) and HelloActionImpl.java (generated by the akkasls codegen). And those are not related to each other at code level. 

Entities doesn't suffer from that issue because the generated code follows the domain name, not the gRPC service.

**Comment by octonato** [comment]
Relates to https://github.com/lightbend/akkaserverless-java-sdk/issues/207

Maybe not worth to find a solution for this. Appending `View` and `Action` may be the easiest solution we have. The `Impl` looks weird for abstract/interface though. 

Pity that views and actions will look different then Entities.

Anyway, I'm leaving this open for now to let it sink a bit more.

**Comment by johanandren** [comment]
One annoying scenario when appending `View` is when the name already contains the name view - in the eventing-shopping-cart `ShoppingCartViewService` leads to the class `ShoppingCartViewServiceView`.

**Comment by patriknw** [comment]
To continue the "hack" we can add `Impl` instead of `View` when the original name contains "View" instead of ends with "View".
