### ISSUE TITLE
Remove valueentity-counter-generated

### ISSUE THREAD

**Issue by patriknw** [lightbend/akkaserverless-java-sdk#245]
or explain why it adds any value

I think the dev roundtrip described in https://github.com/lightbend/akkaserverless-java-sdk/blob/main/CONTRIBUTING.md works fine.

We will have a sbt plugin for the Scala SDK and then we can probably use that also for Java codegen in some builds.

**Comment by patriknw** [comment]
Is this also the reason for why we publish the artifacts with Scala 2.12 dependency instead of 2.13?

see https://github.com/lightbend/akkaserverless-java-sdk/pull/188

**Comment by raboof** [comment]
> or explain why it adds any value
>
> I think the dev roundtrip described in https://github.com/lightbend/akkaserverless-java-sdk/blob/main/CONTRIBUTING.md works fine.

`valueentity-counter-generated` is needed for the `valueentity-counter` sbt subproject, the advantage is we get quick feedback when we change something in the sdk runtime library that breaks a project. The dev roundtrip with `publishLocalM2` also covers that but requires some extra steps to get there. I don't feel strongly about keeping/removing it.

> We will have a sbt plugin for the Scala SDK and then we can probably use that also for Java codegen in some builds.

To make this useful we have to make sure it is the 'current' version of the plugin, not the 'previous' one, which needs some pretty tricky sbt hacks. We actually have something like that right now with the `codegenJavaCompilationTest` (and also do it in akka-grpc), but it does cause trouble from time to time, especially around cross-building/publishing

> Is this also the reason for why we publish the artifacts with Scala 2.12 dependency instead of 2.13? see #188

I'm pretty sure that has nothing to do with `valueentity-counter-generated`, but indeed it might have to do with `codegenJavaCompilationTest`.
