### ISSUE TITLE
Speedup antora make cycle

### ISSUE THREAD

**Issue by patriknw** [lightbend/akkaserverless-java-sdk#279]
Over 1 minute to build docs when developing it is not great. I guess it's the full javadoc and other sbt stuff that is taking much time and not the actual antora build.

Can we have a quick make that is only performing the essentials?

**Comment by pvlugter** [comment]
There are already separate make targets. So first build everything with `make`. If iterating only on the doc content, use `make dev-html` to regenerate the docs. If changing the example snippets in the samples, can use `make examples dev-html` to copy the samples first.
