### ISSUE TITLE
Should View class really be generated for automatic view

### ISSUE THREAD

**Issue by johanandren** [lightbend/akkaserverless-java-sdk#290]
We implemented it so that a view without any `transform_updates: true` methods will anyway generate all classes that a view with update transformations will. This means there is a generated default `emptyState` that throws, but since the view is automatic it is actually never invoked. 

We did it like that to make it easy to enable transform in the protobuf after having generated things, and avoiding to have different code paths in the codegen (for example only generating a `Provider`).

After a discussion with @RayRoestenburg I wonder if this isn't more confusing than we thought when going down that path - could we make it less confusing - either by doing it in a different way or generating some explanatory comment for such cases?

**Comment by patriknw** [comment]
One quick fix could be to only generate `emptyState` differently depending on `transform_updates`. When `true` like it is today. When `false` we could generate a concrete method returning `null` in the abstract class.

**Comment by johanandren** [comment]
That's a good idea, then if toggled to true we'd remove that method and concrete impl won't compile until users add the method. 👍

**Comment by patriknw** [comment]
I'll fix this, before adding docs for views.
