### ISSUE TITLE
Enable it test for eventing sample

### ISSUE THREAD

**Issue by patriknw** [lightbend/akkaserverless-java-sdk#297]
I tried in https://github.com/lightbend/akkaserverless-java-sdk/pull/294 but there is something with pubsub that is not working. Is AkkaServerlessTestkitResource supposed to start the pubsub emulator automatically?

**Comment by johanandren** [comment]
While working on it I only saw them pass locally when manually starting the pub/sub emulator, which is what is mentioned in the README of that sample.

**Comment by pvlugter** [comment]
I think integration testkit just has support for connecting to a running pub/sub emulator. Originally from https://github.com/lightbend/akkaserverless-framework/pull/573.
