### ISSUE TITLE
Immutable replicated data structures

### ISSUE THREAD

**Issue by pvlugter** [lightbend/akkaserverless-java-sdk#298]
Follow up to #83 and #287. Switch the replicated data structures fully to immutable APIs. These are currently mutable APIs but (deep) copied before being passed to command handler methods. Updating methods could also allow chaining.

**Comment by pvlugter** [comment]
I'm looking to get this done today, so the replicated data APIs don't have to change again.

**Comment by patriknw** [comment]
Thanks
