### ISSUE TITLE
Integration tests compilation issues

### ISSUE THREAD

**Issue by octonato** [lightbend/akkaserverless-java-sdk#354]
I notice that we still have some issue with the integration tests maven setup. 

Since the fix for #321, the `src/it/java` is included by IntelliJ as a test source, but it gives compilation error in for the grpc client. 

The grpc client only get compiled if we call `mvn verify -Pit`

Calling `mvn compile -Pit` has no effect. It doesn't compile the test nor it generated the grpc client.

**Comment by johanandren** [comment]
Do you have some more details, is it a specific sample or something? I just now created a project with the 0.7.0 archetype and everything seems to compile fine (I see the compiled `NnnIntegrationTest` in `target/`)

**Comment by octonato** [comment]
It was on the new sample (eventsourced-counter) that I'm adding, but...

The right command should be `mvn test-compile -Pit`. I will test it again.

**Comment by octonato** [comment]
In any case, there is still an issue, because if you import the project in IntelliJ and run `mvn compile`, the grpc client won't be generated. The problem being that the generated tests are triggered by the compile phase from the akkasls plugin.

**Comment by octonato** [comment]
Tested it again, it works with `mvn test-compile`, without `-Pit`. And that's good. 

I think we should instead instruct users to call `mvn test-compile` to generate the files. As such, we get the gRPC client ready for usage and available for IntelliJ.

Another option is to have two generate methods in the mojo. One for the sources and attached to `compile` and one for the test sources attached to `test-compile`. So we only generate test files if `test-compile` is called. 

For the DX, we most make sure that if we generate something all the dependencies must be generate as well.

**Comment by johanandren** [comment]
The gRPC clients are always generated now with the default compile (since #389) so we can close this?

**Comment by patriknw** [comment]
@octonato can we close this now? We always generate grpc client.

**Comment by octonato** [comment]
yes, this is solved.
