### ISSUE TITLE
Instructions for local development don't work on Linux in all cases

### ISSUE THREAD

**Issue by jrudolph** [lightbend/akkaserverless-java-sdk#388]
As observed here [in the forum](https://discuss.lightbend.com/t/java-kickstart-on-ubuntu-linux-16-04-lts-20-04-lts/8429( and also by myself the instructions given in the documentation and in the various example READMEs might not work on Linux.

The basic reason is that the proxy is started using `docker-compose` and the user-function is run on the host computer and binding to `localhost`. The host `localhost` interface is not necessarily accessible from a docker container running with the usual `bridge` networking.

Instead, the user-function should bind to all interfaces or the `docker0` interface in particular. You can achieve that by using

```bash
HOST=0.0.0.0 mvn compile exec:java
```

Is there a better way? If not, maybe that's what we should recommend everywhere.

**Comment by raboof** [comment]
(some related discussion at https://github.com/lightbend/akkaserverless-framework/issues/581 )
