### ISSUE TITLE
Use a different example as Event Sourced entity

### ISSUE THREAD

**Issue by ennru** [lightbend/akkaserverless-java-sdk#39]
The example with a single value being updated doesn't illustrate the principle of Event Sourcing well. We can either use the "counter" example as in the Value entity or come up with something else.

**Comment by octonato** [comment]
This is now implemented in #33, but not yet available in the main branch.

**Comment by octonato** [comment]
I'm closing this one since already implemented and will be integrated in main branch one we finish the repo merging.
