### ISSUE TITLE
Align sample proto directory/file structure

### ISSUE THREAD

**Issue by johanandren** [lightbend/akkaserverless-java-sdk#416]
@mckeeh3 pointed out that we are not consistent with the samples in how the proto files are organized. 

In some (most?) samples we use a single directory, either directly under `proto/` or an additional domain:y name, for example `proto/shoppingcart` where we put all proto files of the service, those files then have different packages to co-exist/have some clear organisation once porto-compiled to Java classes.

In a few samples we instead have organized them according to type of component, so `proto/actions` `proto/value-entities`.

I think Hughs going of view is that we should 1:1 the files with the packages, but I'm not convinced (and there may be consequences of that which I have not thought about).

**Comment by johanandren** [comment]
My own opinion is that a single service should be relatively small and not have a large number of different proto files anyway, and that putting them together in a single directory is convenient and also does not incorrectly give the impression that protobuf correlates the directory and package name structure somehow.

**Comment by johanandren** [comment]
Possibly also something missing from the docs here about how the proto imports vs package names works.

**Comment by pvlugter** [comment]
The [protobuf style guide](https://developers.google.com/protocol-buffers/docs/style) does say that package names and directory structure should be aligned. This is also a default lint rule — so we have this structure in the framework protocols which run `buf` lint.
