### ISSUE TITLE
Different name for the abstract base class

### ISSUE THREAD

**Issue by ennru** [lightbend/akkaserverless-java-sdk#42]
Right now, the abstract base class for the Event Sourced Entity gets the suffix `Interface` which is misleading.

**Comment by octonato** [comment]
I also got that feeling that it should be called `AbsctractSomething`. 

And we can call the implementation `Something` instead of `SomethingImpl`.

**Comment by franciscolopezsancho** [comment]
fixed on https://github.com/lightbend/akkaserverless-java-sdk/pull/99

**Comment by franciscolopezsancho** [comment]
#109
