### ISSUE TITLE
Unmanaged classes sometimes need a second 'compile'

### ISSUE THREAD

**Issue by raboof** [lightbend/akkaserverless-java-sdk#435]
When opening a new project and running `compile`, it seems any missing 'unmanaged' classes are correctly generated into `src/main/scala`, but not actually picked up for that `compile` step. Running `compile` again fixes it.

Perhaps they are created 'too late' to be picked up when sbt checks which files have changed and have to be (re)compiled?

**Comment by patriknw** [comment]
see also https://github.com/lightbend/akkaserverless-java-sdk/issues/454
