### ISSUE TITLE
Compilation error in scripted

### ISSUE THREAD

**Issue by patriknw** [lightbend/akkaserverless-java-sdk#454]
`> compile` results in false compilation error

```
[info] [error] /private/var/folders/xr/nt7rxsy56zqfy3qm4m7kmg4m0000gn/T/sbt_32014332/target/scala-2.13/src_managed/main/akkaserverless/com/example/shoppingcart/view/shopping_cart_view_model/AkkaServerlessFactory.scala:9:72: not found: type ShoppingCartViewServiceImpl
[info] [error]       createShoppingCartViewServiceImpl: Function[ViewCreationContext, ShoppingCartViewServiceImpl]): AkkaServerless = {
[info] [error]
```

That `ShoppingCartViewServiceImpl` and `AkkaServerlessFactory` are in the same package and should compile fine, but I suspect it's something with the managed vs unmanged sources when using scripted.

This works:
```
> protocGenerate
> generateUnmanaged
> compile
```

**Comment by patriknw** [comment]
I can confirm that this problem also exists in the scala-value-entity-customer-registry sample. `compile` twice is needed after a full cleanup.

**Comment by raboof** [comment]
possibly duplicate of #435

**Comment by patriknw** [comment]
ok, thanks
