### ISSUE TITLE
Broken link to Replicated Entities in toc

### ISSUE THREAD

**Issue by patriknw** [lightbend/akkaserverless-java-sdk#455]
Links to https://developer.lightbend.com/docs/akka-serverless/java/replicated-entity-crdt.html (404)

We have `replicated-entity-crdt.adoc` and in index.adoc and nav.adoc we refer to `replicated-entity.adoc`

In replicated-entity-crdt.adoc we have 
```
:page-aliases: replicated-entity.adoc
```

I don't see what is wrong.

https://developer.lightbend.com/docs/akka-serverless/java/replicated-entity.html redirects to replicated-entity-crdt.html (404)

@pvlugter can you take a look?

**Comment by retgits** [comment]
The error I got from Safari is "too many redirects", which made me check the Lightbend Tech Hub repo and I found a redirect there as well (https://github.com/lightbend/techhub/pull/381/files#diff-af806b6137e21571940a3a95d7d810867351e0d67a8619a48b72b001be07f03a), my best guess is that these two redirects keep redirecting. We could give it a quick try and remove the `page-aliases`

**Comment by patriknw** [comment]
Thanks for looking closer att the error.

> We could give it a quick try and remove the page-aliases

ok, but what is the decided place for redirects? Tech Hub or page-aliases?
Let's say we rename or move a page, were do we add the redirect?

**Comment by pvlugter** [comment]
Ok, not something I added. Yes, let's decide on one approach for redirects. The page aliases were added first (such as #400 in this case) so were they not working? The tech hub redirects were only added yesterday.

**Comment by pvlugter** [comment]
The redirect in the dev docs seems to work fine, which will just be the page alias:

https://docs.akkaserverless.dev/java/replicated-entity.html

So that it works both in the dev docs (served from google cloud storage?) and prod docs (from tech hub) shall we keep the page alias and revert the extra redirects in tech hub?

**Comment by retgits** [comment]
The aliases worked perfectly (at least all the ones I tested 😇) and they're easier to add and update

**Comment by pvlugter** [comment]
And it's not that there are two redirects in this case. The tech hub nginx redirect is always going to be applied and it creates a loop itself:

```
location ~ /docs/akka-serverless/java/replicated-entity(.*)$ {
    return 301 https://$developerlightbend/docs/akka-serverless/java/replicated-entity-crdt(.*)$
```

Note that it will match `replicated-entity-crdt` as well, redirecting to itself. If it didn't have the wildcard but was `replicated-entity.html` -> `replicated-entity-crdt.html` then it would work.
