### ISSUE TITLE
Streaming in not possible to use for anything

### ISSUE THREAD

**Issue by johanandren** [lightbend/akkaserverless-java-sdk#463]
Any scenario I can think of requires the user to **run** the incoming `Source` of messages and then make an async reply out of that, but there is currently no access to an `ActorSystem` or a `Materializer` needed to do that. 

Streaming out and bidi streaming is possible since those gives a chance to hand off the stream blueprint for the SDK to materialize/run.

**Comment by johanandren** [comment]
Perhaps we should make the `Materializer` available through `ComponentContext`?

**Comment by patriknw** [comment]
> Perhaps we should make the Materializer available through ComponentContext?

I can't come up with any better alternative. It becomes rather low level Akka Streams stuff but it's already Streams.

**Comment by pvlugter** [comment]
I think the TCK implementation for streaming in just creates its own actor system currently. Making the materializer available does seem like the best option.
