### ISSUE TITLE
Remove WriteConsistency for ReplicatedEntity

### ISSUE THREAD

**Issue by patriknw** [lightbend/akkaserverless-java-sdk#47]
WriteConsistency is a too low level concern in this context.

It should be WriteMajority by default.

Possibly it could be a configuration property.

**Comment by pvlugter** [comment]
I'll start with moving the write consistency from a per-command context-based setting to an overall entity setting.

Given that we don't have read consistency, there's not much need to have a write majority by default, so can leave the default as write local. Write majority may not make much sense to ever use. And I'm assuming that even with write all there's still a small chance of not reading your writes (from the client side) — if the next client request can arrive before the subscribed change events at another instance.
