### ISSUE TITLE
CI testing of unmanaged sources in samples

### ISSUE THREAD

**Issue by patriknw** [lightbend/akkaserverless-java-sdk#486]
Unless I have missed something we are not testing that the generated unmanaged sources for the samples compile correctly. The unmanaged sources are in git and implemented by us.

We could have a CI job that removes src/main/ in the samples and runs sbt/mvn compile.

**Comment by octonato** [comment]
Ok, I see what you mean. Makes sense. 

We can do it after we run the samples, we can have another round that remove all the implementations and do the test-compile

**Comment by patriknw** [comment]
This was fixed.
