### ISSUE TITLE
Shoppingcart quickstart doesn't have a zipfile

### ISSUE THREAD

**Issue by retgits** [lightbend/akkaserverless-java-sdk#502]
The command `akkasls quickstart list` shows two Java quickstarts for which code can be downloaded. 

```
akkasls quickstart list
ID                       NAME                LANGUAGE   OUTPUT_DIR          
customer-registry-java   Customer Registry   java       customer-registry   
shopping-cart-java       Shopping Cart       java       shopping-cart    
```

For the `customer-registry-java` quickstart the zip file exists, but for `shopping-cart-java` it does not. I checked the https://github.com/lightbend/akkaserverless-java-sdk/tree/docs/current/docs/build/src/managed/modules/java/attachments and there's no zip file there.

**Comment by pvlugter** [comment]
Added in #442 and https://github.com/lightbend/akkaserverless-docs/pull/949 but SDK docs haven't been published since. I've manually deployed the SDK docs, and triggered the auto PR for prod docs (otherwise it doesn't have anything to rebuild). Should be available once tech hub builds.

**Comment by pvlugter** [comment]
Ok, the zip file is available now. But those quickstart docs have broken includes because of directory structure change in #473. Would be better if the docs failed to build (we have that with the SDK docs with the latest version of antora). I'll fix those too.

**Comment by pvlugter** [comment]
Zip file available now so closing this. Updates to proto directory structure in https://github.com/lightbend/akkaserverless-docs/pull/963.

**Comment by retgits** [comment]
Thanks a lot @pvlugter
