### ISSUE TITLE
Generate abstract methods for command handlers

### ISSUE THREAD

**Issue by patriknw** [lightbend/akkaserverless-java-sdk#53]
So that the java compiler will notice when a new rpc is added, or changed.

Currently it generates 3 methods for each command handler and the user has to choose which one to override. That is just confusing and missing implementation will only be detected at runtime instead of compile time.

Additionally, abstract methods are nice in an IDE because it's easy to click the compilation error and add the missing method.

**Comment by octonato** [comment]
Done in #152
