### ISSUE TITLE
duplicate classes between Java and Scala SDK

### ISSUE THREAD

**Issue by raboof** [lightbend/akkaserverless-java-sdk#535]
I see some classes, such as com/google/api/ResourceReference.class, be included in both the Java and the Scala SDK resources. Since the Scala SDK depends on the Java SDK, only generating them in the Java SDK should likely be sufficient? Or are they actually conflicting?

**Comment by johanandren** [comment]
I agree only generating once sounds better.

**Comment by pvlugter** [comment]
Yes, only generating in Java SDK sounds good. Would also prevent #542.
