### ISSUE TITLE
Add unit tests to the Eventing Shopping Cart example

### ISSUE THREAD

**Issue by patriknw** [lightbend/akkaserverless-java-sdk#54]
...and use those in the docs to show the test kit and unit testing.

**Comment by patriknw** [comment]
However, this might be less relevant nowadays since I think we use other examples in the documentation? Anyway, if we keep the example it should have tests.

**Comment by johanandren** [comment]
Doing this as it will also let me work through the test kit which I haven't used before.

**Comment by johanandren** [comment]
After digging a bit here, the eventing sample has a integration test, but no unit tests. I think I misinterpreted this issue as there being something more akin to in-jvm testkit but the SDK testkit is for running integration tests against proxy in docker with the help of test-containers, not unit tests?

**Comment by kikiya** [comment]
The unit tests should be using the js testkit. 

I think the docs have been updated to show this. I just reviewed a PR for a tutorial using the e-commerce sample to show unit testing with js testkit. 

The main issue I saw with the current format is it requires manually downloading the testkit and I think it should be part of the SDK instead. @johanandren @octonato

**Comment by johanandren** [comment]
This is the Java SDK though, and the testkit is part of the SDK set of artifacts and included in samples as a regular dependency. 

Just that it doesn't have any specific support for unit tests (as in quick in-process tests) but integration tests where it spins up the proxy in dev mode in a docker container and runs tests against that. So maybe it is just a terminology confusion here (unit tests vs integration tests run in tests written with junit).

**Comment by johanandren** [comment]
Depends on #118 now then
