### ISSUE TITLE
'unmanaged code'-comment is easy to miss

### ISSUE THREAD

**Issue by raboof** [lightbend/akkaserverless-java-sdk#549]
For code that we generate once and then has to be maintained by the user, we produce a comment explaining this at the top of this file. However, this is easy to miss, especially in IntelliJ which collapses it by default:

![comment](https://user-images.githubusercontent.com/131856/135600816-730c7154-7778-46ce-96de-428233ca96ec.png)

This is confusing for the first user experience, as most users will start by renaming their service. I think we should move it to the comment above the class rather than at the top of the file.

**Comment by patriknw** [comment]
Sounds good to move it to a more visible place
