### ISSUE TITLE
Testing strategies

### ISSUE THREAD

**Issue by octonato** [lightbend/akkaserverless-java-sdk#56]
Since we are moving the maven plugin, the archetypes and the codegen-java under the java-sdk, we will be able to better glue the pieces and run several tests. 

I will sketch here what I have in mind so others can comment and bring in other ideas. 

We have few parts to integrate

* java-sdk (sbt project) 
* codegen - depends on java-sdk (sbt project) 
* plugin - depends on codegen
* archetypes - depends on all the above
* samples - depends on sdk and plugin (indirectly on codegen)

### Plugin and Codegen

The plugin is now testing the codegen based on a simple descriptor. We generate code and then we verify if the files were emitted. The codegen itself has more tests and we should keep and improve as we go. 

### Samples

The samples are now tested against the current SDK (current as in the branch, not published artifacts) and uses a published codegen.

Once we move the codegen here, the samples test should run against the current codegen as well.   

### Archetypes 

Archetypes are minimally tested. As of today, we only generated a new project from it an run `mvn verify`. 

A better test would be to generate a new project, copy some implementation (domain + tests) and run the tests and integration tests. For example, on each new build, we could generate a new `valueentity-counter`, copy key files from `samples/valueentity-counter` and run the full tests. 

That will confirm a two things: codegen generates the right pieces and archetype `pom.xml` is what needs to be.

Note, this is not the same as testing the samples. The idea of copying implementation classes from the samples it to force a start from scratch and be able to assess if all the new generated code plus the pom.xml from the archetype is correct.

Another set of tests, would be to build the user service container, deploy it with the proxy and run some integration tests.

**Comment by franciscolopezsancho** [comment]
I'll start creating a script that 

- clones the java-sdk
- install the archetypes on local
- generate a new project from that local archetype 
- run both tests (unit and it)
- and copy the relevant files from samples (maybe one by one starting with the Impl) while running the tests.

**Comment by octonato** [comment]
You mean one script that does that all? 

This is better done by the CI using its scripting facilities. At the end, it's the same, but there are a few other things already in place.

**Comment by franciscolopezsancho** [comment]
I don't know how many of all the cases we are going to tackle with this but I thought it could be a useful first iteration. I totally agree that done in CI is the way to go. What I thought is first testing all this in local to have it fleshed out and later if we find it useful, yeah, moving it to CI. Makes sense or you would rather start developing it in CI?

**Comment by octonato** [comment]
That's fine. It's good to try it locally first since interacting with CI is mostly a slow process. 

Ultimately, whatever strategy we pick, we want it running on CI and that for each PR.

**Comment by franciscolopezsancho** [comment]
I created https://github.com/lightbend/akkaserverless-java-sdk/pull/57 to start with @octonato

**Comment by franciscolopezsancho** [comment]
In the Makefile we have `run-test-impl` that tests if sample and codegen are in sync. In order for this to work the codegen should not create test asserting for failure. I uploaded the file `trinity/src/test/com/example/domain/CounterTest.java` which has an implementation that passes as long the CounterImpl contain the required methods. If the codegen would created such a file `CounterTest` we then could do the `run-test-impl` and test the sample is in sync with the codegen.  LMKWYT

**Comment by franciscolopezsancho** [comment]
I removed the mocking creation from the codegen. This is how it would look the PR https://github.com/franciscolopezsancho/akkaserverless-codegen/pull/1

**Comment by franciscolopezsancho** [comment]
I added to that PR:
- generation of Tests and [Counter]Impl such is not mocking anything and `mvn verify` pass in a clean project 
- generation of Main. It was broken by missing SERVICE variable. `mvn verify -Pit` pass in a clean project 

I think that's ready to merge @octonato

**Comment by johanandren** [comment]
For the record: Inclusion of code-gen now has brought integration tests in the form of using the current state of codegen and maven plugin with the sample projects which then run integration tests against a dev mode proxy as part of PR validation etc.

**Comment by patriknw** [comment]
I guess this has been done.
