### ISSUE TITLE
Build maven plugin and archetype using sbt

### ISSUE THREAD

**Issue by octonato** [lightbend/akkaserverless-java-sdk#58]
When migrating the maven plugin and archetypes here, I keep it as maven project. But it requires some hacking to build it using the same version as the sbt project. 

Lagom has a maven plugin and archetype that are build with sbt. I think we should do the same here. 

Then we don't need to hack things around and when publish we only need to deal with sbt release. That will make our life easier.

**Comment by raboof** [comment]
> Lagom has a maven plugin and archetype that are build with sbt. I think we should do the same here

Akka gRPC does the same thing. This requires some massaging since we can't simply use the maven-plugin-tools anymore, and instead have to introduce our own `project/SbtMavenPlugin.scala`. I wonder if this is really worth it...

**Comment by octonato** [comment]
Is `SbtMavenPlugin.scala` the only thing we need? 

The advantage of doing everything from the sbt is that we don't need extra tweaks to align the versions and the publishing gets simplified.

**Comment by raboof** [comment]
> Is `SbtMavenPlugin.scala` the only thing we need?

it seems we also need to 'manually' write the plugin.xml (https://github.com/lagom/lagom/blob/master/dev/maven-plugin/src/main/maven/plugin.xml) instead of having it generated for us from the Mojo code and comments. Seems tricky to keep in sync, unless I'm missing something?

**Comment by octonato** [comment]
@raboof, only seeing your reaction now. Yes indeed, we will need to keep it aligned, but I don't think that's tricky. Some extra work, but feasible. 

On the other hand, we do have a solution now that works. A little hacky, but it works. So, I'm closing this issue. I don't think that the situation we have now is such a terrible hack that would justify refactoring it. 

We can re-assess if that really bites us in the future.
