### ISSUE TITLE
Release Java / Scala SDK 0.9.0

### ISSUE THREAD

**Issue by ennru** [lightbend/akkaserverless-java-sdk#636]
# Releasing Akka Serverless Java/Scala SDKs

- [x] Make sure all important PRs have been merged
- [x] Check that the [latest build](https://app.circleci.com/pipelines/github/lightbend/akkaserverless-java-sdk) successfully finished
- [x] Edit the [draft release notes](https://github.com/lightbend/akkaserverless-java-sdk/releases) and create the appropriate tag
	- CI will automatically publish to Sonatype OSSRH (Maven Central) based on the tag
	- CI will update the docs/current branch
- [x] Update the sdk version in samples and maven plugin
  - [x] Update the `akkaserverless-sdk.version` in the `samples/*/pom.xml` files to the released version.
  - [x] Update the `akkaserverless-sdk.version` default value in the `samples/scala-*/project/plugins.sbt` files to the release version
  - [x] version in maven-java/**/pom.xml
- [ ] Update the [supported version in the main docs](https://github.com/lightbend/akkaserverless-docs/blob/master/docs/modules/ROOT/partials/include.adoc#L21) if relevant (affects [Supported Versions](https://developer.lightbend.com/docs/akka-serverless/setting-up/index.html#_supported_languages))
- [x] Release the Akka Serverless documentation to get the SDK docs updates published
- [x] Move appropriate things on [the board](https://github.com/orgs/lightbend/projects/8?card_filter_query=label%3Aas-framework) to "Shipped"
- [x] Announce in [the forum](https://discuss.lightbend.com/c/akka-serverless/40)
  - tag with Akka Serverless, releases and announcement
- [x] Inform Lightbend marketing and engineering if it's a noteworthy release

**Comment by patriknw** [comment]
good, will you also turn this into a template and update the RELEASING?

**Comment by ennru** [comment]
Yes. After the release so that we know it works out.
