### ISSUE TITLE
Document entity id auto-generation

### ISSUE THREAD

**Issue by johanandren** [lightbend/akkaserverless-java-sdk#755]
Once next proxy version (0.8.6) is deployed we should add docs about that feature, and also update the current composition/Action as Controller docs which shows how to generate UUID to perhaps create some other id based on time and or message properties, and also mention the auto-id in that section.

**Comment by johanandren** [comment]
Proxy PR for the feature: https://github.com/lightbend/akkaserverless-framework/pull/1026

**Comment by johanandren** [comment]
Feature now in prod

**Comment by patriknw** [comment]
@jroper will you add this documentation?

**Comment by jroper** [comment]
Sure, I can do that.
