### ISSUE TITLE
docs: show CLI instead of referring to UI in quickstarts

### ISSUE THREAD

**Issue by ennru** [lightbend/akkaserverless-java-sdk#769]
The steps in the quickstart docs need to be updated to show CLI commands for creating projects and routes.

- [x] https://developer.lightbend.com/docs/akka-serverless/java/quickstart/cr-value-entity-java.html#_package_and_deploy_your_service
- [x] https://developer.lightbend.com/docs/akka-serverless/java/quickstart/cr-value-entity-views-java.html#deploy
- [x] https://developer.lightbend.com/docs/akka-serverless/java/quickstart/sc-eventsourced-entity-java.html#_package_and_deploy_your_service
- [x] https://developer.lightbend.com/docs/akka-serverless/java/quickstart/cr-value-entity-scala.html#_package_and_deploy_your_service

**Comment by pvlugter** [comment]
I'll go through and update these.
