### ISSUE TITLE
Messages outside service proto are wrongly referenced

### ISSUE THREAD

**Issue by octonato** [lightbend/akkaserverless-java-sdk#82]
Reproducer https://github.com/octonato/counter-action-view

In the above reproducer, `ref_id.proto` is a standalone definition that is imported in both `counter_api.proto` and `counter_action.proto`. 

The generate protobuf for RefId is `com.example.RefIdProto`, but in the generated code we reference it as `Com.example.RefId.placeholder`. Note as well the uppercase `C` at beginning. 

For example, the generated action is: 

```java
public abstract class CounterActionInterface {
    @Handler
    public abstract Reply<Com.example.RefId.placeholder.RefId> newCounter(Empty event, ActionContext ctx);
}
```

but it should be 

```java
public abstract class CounterActionInterface {
    @Handler
    public abstract Reply<com.example.RefIdProto.RefId> newCounter(Empty event, ActionContext ctx);
}
```

Or in `MainComponentRegistrations`

```java
registerValueEntity(
    CounterImpl.class,
    CounterApi.getDescriptor().findServiceByName("CounterService"),
    CounterDomain.getDescriptor(),
    Com.example.RefId.placeholder.getDescriptor(),
    EmptyProto.getDescriptor()
)
```

should be

```java
registerValueEntity(
    CounterImpl.class,
    CounterApi.getDescriptor().findServiceByName("CounterService"),
    CounterDomain.getDescriptor(),
    com.example.RefIdProto.getDescriptor(),
    EmptyProto.getDescriptor()
)
```

**Comment by patriknw** [comment]
I tried this and can't reproduce with the new codegen.
