### ISSUE TITLE
Java - register components in the impl classes

### ISSUE THREAD

**Issue by mckeeh3** [lightbend/akkaserverless-java-sdk#84]
Each component impl class includes a register method

~~~java
  public static void register(AkkaServerless akkaServerless) {
    akkaServerless.registerValueEntity(
      CounterImpl.class,
      CounterApi.getDescriptor().findServiceByName("CounterService"),
      CounterDomain.getDescriptor()
    );
  }
~~~

In the Main.main( ... ) method

~~~java
    final var service = new AkkaServerless();

    CounterImpl.register(service);
    MyActionImpl.register(service);
    ProductsByPostalViewImpl.register(service);
    CustomerOrdersViewImpl.register(service);

    service.start().toCompletableFuture().get();
~~~

**Comment by raboof** [comment]
With the trend in #62 to allow the codegen to dictate more of where things must go, it looks like we can likely make the registration simpler, and hide more of the complexity in generated code that the user doesn't have to care about.

**Comment by patriknw** [comment]
With the new codegen we have a slightly different solution than what is proposed here.
