### ISSUE TITLE
Should we develop a basic protobuf editor?

### ISSUE THREAD

**Issue by huntc** [lightbend/akkaserverless-java-sdk#88]
We've been toying with the idea of alternate editor for protobuf and Visual Studio Code projects (VSC). VSC has been targeted specifically as it also permits us to explore the ability to provide the same editing experience for web-based applications such as the Akka Serverless web UI.

Our goal continues here to be one of reducing the number of new things a developer must take on to become successful with Akka Serverless. Following on from leveraging the native tooling a developer should already be familiar with (npm/js == npx, Maven/Java == archetypes), we think that have an extension for VS Code focused sharply on protobuf editing in the context of Akka Serverless, should feel intuitive. Furthermore, the experience of this editor, while we can promote its usage and easy-installation within VSC, is opt-in. There will certainly be developers preferring to edit their own protobuf.

This issue has been designed to encourage feedback. To provoke that, here's a short video of what we've prototyped to-date:

https://drive.google.com/file/d/1Gicx-PqI5tMB2wP_Z_NAenZAOSyg-n34/view?usp=sharing

If there is sufficient interest and approval, we will then develop a solution design to capture this thinking and feedback.

**Comment by patriknw** [comment]
Closing (at least until it comes in as a feature request)
