### ISSUE TITLE
Need to optimize mvn builds in CI

### ISSUE THREAD

**Issue by octonato** [lightbend/akkaserverless-java-sdk#9]
We are starting to run mvn for the samples (see #8) and I notice that it's download all the artifacts each time. 

That's strange, because CircleCI mention that it caches the artifacts. There must be something missing in the yml.

**Comment by ennru** [comment]
CircleCI requires explicit caching of Maven dependencies, but this is even a monorepo which requires special handling.

- https://circleci.com/docs/2.0/language-java-maven/#caching-dependencies
- https://circleci.com/docs/2.0/caching/#using-caching-in-monorepos

**Comment by octonato** [comment]
Happening in #44
